### ISSUE TITLE
An example requires `CSV.jl` installed

### ISSUE THREAD

**Issue by singularitti** [Arkoniak/UrlDownload.jl#17]
The first example in `README.md` requires `CSV` to be installed:
```julia
using UrlDownload
using DataFrames

url = "https://raw.githubusercontent.com/Arkoniak/UrlDownload.jl/master/data/ext.csv"

julia> df = urldownload(url) |> DataFrame
ERROR: ArgumentError: Package CSV not found in current path:
- Run `import Pkg; Pkg.add("CSV")` to install the CSV package.
```

Is it expected? If so, maybe a `using CSV` should also be added to the doc.

**Comment by Arkoniak** [comment]
Yes, this is expected. For this package to work, you should install necessary packages (this Error which you received tells you explicitly which one you need), but there is no need to add `using CSV`, since package import packages on it's own. 

Thank you for raising this issue, I should add this explanation to README.
